apiVersion: v2
appVersion: 1.4.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Helm chart to deploy airbyte-worker
name: worker
type: application
version: 1.4.0
